### ISSUE TITLE
Wrong -rsv option

### ISSUE THREAD

**Issue by rperrell** [qwazer/scheme2ddl#35]
Documentation says

       -rsv,                      replace actual sequence values with 1 
      --replace-sequence-values,

but the correct options are -fsv and --filter-sequence-values

Main.java line 308

            }   else if ((arg.equals("-fsv") || arg.equals("--filter-sequence-values"))) {
                replaceSequenceValues = true;

**Comment by qwazer** [comment]
fixed in https://github.com/qwazer/scheme2ddl/releases/tag/v2.3.12
