### ISSUE TITLE
Unify command line parameter quoting

### ISSUE THREAD

**Issue by neekibo** [qwazer/scheme2ddl#36]
Parameter -f, --filter does not allow single quotes and parameter -tf, --type-filter needs single quotes to work.

Example to get only the ddl for table filter: -f tickets -tf 'table'

**Comment by qwazer** [comment]
this is related to https://github.com/qwazer/scheme2ddl/pull/27

**Comment by arno82** [comment]
OK, I'd guess we want single quotes for -f as well, so I will investigate and deliver a patch for this.

**Comment by arno82** [comment]
Did the check in for Main.java right now.
