### ISSUE TITLE
No Primary keys info in produced ddl

### ISSUE THREAD

**Issue by ostrha1** [qwazer/scheme2ddl#38]
ALTER TABLE t DROP PRIMARY KEY;
ALTER TABLE t add PRIMARY KEY(c1,c2) ;

**Comment by arno82** [comment]
I get this PK constraints after the create table statement. For example:
ALTER TABLE "scheme"."tablename" ADD CONSTRAINT "xxx_PK" PRIMARY KEY ("ID");
which creates the constraint and implicitly the above mentioned "add primary key", so my table has a defined PK afterwards.
