### ISSUE TITLE
SCHEDULER PROGRAMS not exported

### ISSUE THREAD

**Issue by andyluu85** [qwazer/scheme2ddl#40]
SCHEDULER PROGRAMS does not seem to be exported even though SCHEDULER JOB does

**Comment by arno82** [comment]
Did you use the latest sourcecode from git?
I checked in a fix for this two month ago.
If you don't have this line in TypeNamesUtil.java in the map2TypeForDBMS class:
    if (type.equals("PROGRAM"))
            return "PROCOBJ";

then you should use the latest sourcecode and try again.

**Comment by arno82** [comment]
I checked the git source again and saw that my commit isn't there. I'm going to check this and leave you a message here afterwards.

**Comment by arno82** [comment]
Alright, the commit wasn't synced back to GIT, so I did it now:
https://github.com/qwazer/scheme2ddl/commit/f25550554272998bc143e837ccbd15e374a90c1a

You should try again with this piece of code.

**Comment by andyluu85** [comment]
I am pretty new to github. Could you provide me with a guide as to how to build the code? Thank you!

**Comment by andyluu85** [comment]
PROGRAM are now exported with the latest commit

**Comment by arno82** [comment]
Perfect. So I close the issue.

**Comment by qwazer** [comment]
Thanks, Arno. I'll create new release with your latest commits

**Comment by qwazer** [comment]
Included in release v2.3.13

**Comment by arno82** [comment]
Hi.

No problem.

Did you think about my offer:
https://github.com/qwazer/scheme2ddl/issues/37

We have this in use for quite a while and it works perfect.

BR,
Arno
