### ISSUE TITLE
Make fully executable jar for Unix systems with spring boot or other maven plugins

### ISSUE THREAD

**Issue by qwazer** [qwazer/scheme2ddl#45]
http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

**Comment by ostrha1** [comment]
``
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- pom.xml	(date 1474024783000)
+++ pom.xml	(date 1474024845000)
@@ -7,6 +7,12 @@
     <version>2.3.13-SNAPSHOT</version>
     <packaging>jar</packaging>
 
+    <parent>
+        <groupId>org.springframework.boot</groupId>
+        <artifactId>spring-boot-starter-parent</artifactId>
+        <version>1.4.0.RELEASE</version>
+    </parent>
+
     <url>http://scheme2ddl.googlecode.com</url>
 
     <scm>
@@ -36,47 +42,21 @@
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <bintray.repo>qwazer/maven</bintray.repo>
         <bintray.package>scheme2ddl</bintray.package>
-        <spring.framework.version>3.2.13.RELEASE</spring.framework.version>
-        <spring.batch.version>2.2.7.RELEASE</spring.batch.version>
-        <org.aspectj.version>1.7.3</org.aspectj.version>
     </properties>
 
 
     <build>
         <plugins>
             <plugin>
-                <groupId>org.apache.maven.plugins</groupId>
-                <artifactId>maven-shade-plugin</artifactId>
-                <version>2.3</version>
+                <groupId>org.springframework.boot</groupId>
+                <artifactId>spring-boot-maven-plugin</artifactId>
                 <configuration>
-                    <transformers>
-                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
-                            <manifestEntries>
-                                <Main-Class>com.googlecode.scheme2ddl.Main</Main-Class>
-                                <Implementation-Version>${project.version}</Implementation-Version>
-                            </manifestEntries>
-                        </transformer>
-                        <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
-                            <resource>META-INF/spring.handlers</resource>
-                        </transformer>
-                        <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
-                            <resource>META-INF/spring.schemas</resource>
-                        </transformer>
-                    </transformers>
+                    <executable>true</executable>
                 </configuration>
-                <executions>
-                    <execution>
-                        <phase>package</phase>
-                        <goals>
-                            <goal>shade</goal>
-                        </goals>
-                    </execution>
-                </executions>
             </plugin>
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-release-plugin</artifactId>
-                <version>2.5.1</version>
                 <configuration>
                     <tagNameFormat>v@{project.version}</tagNameFormat>
                     <useReleaseProfile>false</useReleaseProfile>
@@ -87,7 +67,7 @@
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-compiler-plugin</artifactId>
-                <version>3.2</version>
+                <version>3.5.1</version>
                 <configuration>
                     <source>1.5</source>
                     <target>1.5</target>
@@ -98,19 +78,21 @@
 
     <dependencies>
         <dependency>
-            <groupId>org.springframework.batch</groupId>
-            <artifactId>spring-batch-core</artifactId>
-            <version>${spring.batch.version}</version>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-batch</artifactId>
         </dependency>
         <dependency>
-            <groupId>org.springframework</groupId>
-            <artifactId>spring-jdbc</artifactId>
-            <version>${spring.framework.version}</version>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-aop</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-jdbc</artifactId>
         </dependency>
         <dependency>
             <groupId>commons-io</groupId>
             <artifactId>commons-io</artifactId>
-            <version>2.4</version>
+            <version>2.5</version>
         </dependency>
         <dependency>
             <groupId>log4j</groupId>
@@ -127,21 +109,9 @@
         <dependency>
             <groupId>com.oracle</groupId>
             <artifactId>ojdbc5</artifactId>
-            <version>11.2.0.3.0</version>
+            <version>11.1.0.6.0</version>
         </dependency>
 
-        <dependency>
-            <groupId>org.springframework</groupId>
-            <artifactId>spring-aop</artifactId>
-            <version>${spring.framework.version}</version>
-        </dependency>
-
-        <dependency>
-            <groupId>org.aspectj</groupId>
-            <artifactId>aspectjweaver</artifactId>
-            <version>${org.aspectj.version}</version>
-        </dependency>
-
 
         <dependency>
             <groupId>junit</groupId>
@@ -149,6 +119,12 @@
             <version>4.11</version>
             <scope>test</scope>
         </dependency>
+
+        <dependency>
+            <groupId>commons-logging</groupId>
+            <artifactId>commons-logging</artifactId>
+            <version>1.2</version>
+        </dependency>
     </dependencies>
 
 
Index: src/main/java/com/googlecode/scheme2ddl/dao/ConnectionDaoImpl.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/com/googlecode/scheme2ddl/dao/ConnectionDaoImpl.java	(date 1474024783000)
+++ src/main/java/com/googlecode/scheme2ddl/dao/ConnectionDaoImpl.java	(date 1474024845000)
@@ -13,7 +13,7 @@
 
     public boolean isConnectionAvailable() {
         try {
-            getJdbcTemplate().queryForInt("select 1 from dual");
+            getJdbcTemplate().queryForObject("select 1 from dual", Integer.class) ;
         } catch (DataAccessException e) {
             return false;
         }
``

**Comment by ostrha1** [comment]
````
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- pom.xml	(date 1474024845000)
+++ pom.xml	(date 1474027715000)
@@ -90,16 +90,14 @@
             <artifactId>spring-boot-starter-jdbc</artifactId>
         </dependency>
         <dependency>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-logging</artifactId>
+        </dependency>
+        <dependency>
             <groupId>commons-io</groupId>
             <artifactId>commons-io</artifactId>
             <version>2.5</version>
         </dependency>
-        <dependency>
-            <groupId>log4j</groupId>
-            <artifactId>log4j</artifactId>
-            <version>1.2.17</version>
-            <scope>runtime</scope>
-        </dependency>
         <!--Unfortunately due the binary license there is no public repository with the Oracle Driver JAR.
         Will try to download it from otn-maven-repo
 
@@ -120,11 +118,6 @@
             <scope>test</scope>
         </dependency>
 
-        <dependency>
-            <groupId>commons-logging</groupId>
-            <artifactId>commons-logging</artifactId>
-            <version>1.2</version>
-        </dependency>
     </dependencies>
 
 
Index: src/main/resources/logback.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/resources/logback.xml	(date 1474027715000)
+++ src/main/resources/logback.xml	(date 1474027715000)
@@ -0,0 +1,5 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<configuration>
+    <include resource="org/springframework/boot/logging/logback/base.xml"/>
+    <logger name="org.springframework" level="INFO"/>
+</configuration>
\ No newline at end of file
Index: src/main/resources/log4j.properties
===================================================================
--- src/main/resources/log4j.properties	(date 1474024845000)
+++ src/main/resources/log4j.properties	(date 1474024845000)
@@ -1,10 +0,0 @@
-log4j.rootCategory=INFO, stdout
-
-log4j.appender.stdout=org.apache.log4j.ConsoleAppender
-log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
-log4j.appender.stdout.layout.ConversionPattern=%m%n
-
-log4j.category.org.springframework=WARN
-#log4j.category.org.springframework.jdbc=TRACE
-#log4j.category.org.springframework.batch=TRACE
-#log4j.category.com.googlecode.scheme2ddl=TRACE
\ No newline at end of file
````

**Comment by qwazer** [comment]
https://github.com/qwazer/scheme2ddl/releases/tag/v2.4.0
