### ISSUE TITLE
Project still active ? Accepting PR ?

### ISSUE THREAD

**Issue by gquerret** [qwazer/scheme2ddl#58]
I was looking for a way to dump an oracle schema (to store it in Git) and found this project which seems to do what I'm looking for. It seems there are no commits and new releases since 2018 so I was wondering if the project was still active or not. Or if it was superseded by another project or technology to manage Oracle DB schema ? I'm new in the Oracle world so learning new things every day...
And do you accept pull requests ? I'd like to change a thing or two, so wondering if I do that in an internal repository, or if I open a PR.

**Comment by qwazer** [comment]
HI. The project is mostly frozen as you can see. I have ideas for improvements but have no time and energy to complete it. My motivation is not very high, maybe becosue I didn't use Oracle DB at least 5 years already.

**Comment by gquerret** [comment]
If my project is confirmed, I'll then push my changes to my fork and open a PR. I'll let you decide if you want to merge changes or not. Thank you !
