### ISSUE TITLE
When I export the procedure with Chinese, the Chinese in file can not read. 

### ISSUE THREAD

**Issue by spyman1802** [qwazer/scheme2ddl#63]
As tile. I check the source and found the reason.  
In UserObjectWriter.java, can you save the file with utf-8 encoding?
I tested.  If save the file using utf-8 encoding, the Chinese in file can read. 
![image](https://user-images.githubusercontent.com/28353653/126609855-ad584217-9d52-4202-a713-c5a54ea5eaca.png)

**Comment by qwazer** [comment]
Thanks for reporting. Fixed in release 2.4.4
